audio_data:
  type: "log"
  sampling_rate: 16000
  window_size: 0.02
  window_stride: 0.01
  window: 'hamming'

model:
  type: transducer
  cnn_encoder:
    local_  cnn_encoder: 
        kernel_size: 5
        stride: 1
    global_cnn_encoder:
        n_layers: 1
        kernel_size_pw: 1
        kernel_size_dw: 3
        stride: 1
        input_dim: 12288   # 64*80
        hidden_dim: 24576
        n_dropout: 0.1
    feature_dim: 640
  enc:
      type: lstm
      hidden_size: 320
      output_size: 320
      n_layers: 4
      bidirectional: False
  dec:
      type: lstm
      embedding_size: 512
      hidden_size: 512
      output_size: 320
      n_layers: 2
  joint:
      input_size: 640
      inner_size: 512

  vocab_size: 4866
  feature_dim: 640
  dropout: 0.3
  name : 'conv-rnnt'
  share_weight: False
  

training:
  epochs: 100
  batch_size: 1
  save_path: "/data/npl/Speech2Text/conv-rnnt/save_folder"
  train_path : "/data/npl/Speech2Text/conv-rnnt/data/train_w2i.json"
  dev_path : "/data/npl/Speech2Text/conv-rnnt/data/test_w2i.json"
  test_path : "/data/npl/Speech2Text/conv-rnnt/data/test_w2i.json"
  vocab_path : "/data/npl/Speech2Text/conv-rnnt/data/vocab_w2i.json"
  reload: False


optim:
  type: adam
  lr: 0.002
  weight_decay: 0.0001
  decay_rate: 0.01



rnnt_loss:
  blank: 4
  reduction: "mean" 