training:
  epochs: 100
  batch_size: 1
  save_path: "C:\\HK6\\speech2text-main\\transformer_transducer\\save_folder"
  train_path : "C:\\paper\\raw_data\\Vietnamese-Speech-to-Text-datasets\\ViVOS\\train_w2i.json"
  dev_path : "C:\\paper\\raw_data\\Vietnamese-Speech-to-Text-datasets\\ViVOS\\test_w2i.json"
  test_path : "C:\\paper\\raw_data\\Vietnamese-Speech-to-Text-datasets\\ViVOS\\test_w2i.json"
  vocab_path : "C:\\paper\\raw_data\\Vietnamese-Speech-to-Text-datasets\\ViVOS\\vocab_w2i.json"
  reload: False
  


# optimizer:
#   name: Adam
#   lr: 0.0001
#   weight_decay: 0.0001
optim:
  type: sgd
  lr: 0.0001
  momentum: 0.9
  weight_decay: 0
  begin_to_adjust_lr: 60
  nesterov: None
  decay_rate: 0.5


model:
  in_features: 80
  n_layers: 4
  n_dec_layers: 2
  d_model: 256
  ff_size: 1024
  h: 4
  joint_size: 512
  enc_left_size: 512
  enc_right_size: 512
  dec_left_size: 512
  dec_right_size: 512
  p_dropout: 0.1
  model_name: "transformer_transducer"



rnnt_loss:
  blank: 4
  reduction: "mean" 


