training:
  epochs: 100
  batch_size: 1
  save_path: "save_folder/"
  train_path : "data/train.json"
  dev_path : "data/test.json"
  test_path : "data/test.json"
  vocab_path : "data/vocab.json"
  reload: False
  


# optimizer:
#   name: Adam
#   lr: 0.0001
#   weight_decay: 0.0001
optim:
  type: sgd
  lr: 0.0001
  momentum: 0.9
  weight_decay: 0
  begin_to_adjust_lr: 60
  nesterov: None
  decay_rate: 0.5


model:
  in_features: 80
  n_layers: 4
  n_dec_layers: 2
  d_model: 256
  ff_size: 1024
  h: 4
  joint_size: 512
  enc_left_size: 512
  enc_right_size: 512
  dec_left_size: 512
  dec_right_size: 512
  p_dropout: 0.1
  model_name: "transformer_transducer"



rnnt_loss:
  blank: 4
  reduction: "mean" 


